dashboard:
  image: stephenwzl/parse-dashboard:latest
  ports: 
    - "4040:4040"
parse:
  #build: ./parse-server
  image: stephenwzl/www_parse:latest
  ports:
    - "1337:1337"
  links:
    - mongodb:MONGODB_URL

mongodb:
  image: mongo:latest
  expose:
    - 27017
  volumes:
    - ./database/:/data/db
