nodejs:  
  build: ./nodejs
  ports:
    - "3000:3000"
  volumes:
    - ./app/src/:/data/app
  links:
    - mongodb:mongodb

mongodb:
  image: mongo:latest
  ports:
    - "27017:27017"
  volumes:
    - ./database/:/data/db
